Apuntes de mis hojas:

Stories: Country. Person. Individual. Self-made man. I am "X"
Test  Heider-Simmel.
Paradoleidile

Start as close as possible to the ending. But don't spoil the ending.

Data Storytelling: uses the 2 most effective tools: visualization (eyes) and narrative (mind).

Data always needs a context (100111010101 is nothing without a context).

# Viz
Gestalt: there are principles in how we see things. 
Ilusiones opticas.

# Comunicacion: influence how we must tell a story. 

Example: public speaking - making a dramatic pause is key to public speaking, but not in a 1-1 conversation.
Ask for feedback, that's the way.

AVoid death by powerpoint. Zombification!

Preparando el plato:
- # minutos = # slides
- Considera tu audiencia. Tienes una deuda temporal con la humanidad. ¿QUien toma la decision? ¿que debe saber?
- Objetivo: ¿que decision se toma despues?
- Construye el final. Siempre. No improvises tu final.

COndimentos:
- Hazlo personal. Deberia ser como tu ropa interior. No deberia ser facil de traspasar.
- Despiadada simplicidad. PPT is not a repport. Best communicators are simplifiers. Avoid jargon.
- Always raise the stakes. 
- Speaker is not the protagonist. Each person is the protagonist of their own life - and they must suffer some change.
- Include emotions. Engineer them into your slide deck.
- Iterate and learn. 


Test the Heider-Simmel  (1994): We are story animals. 
Paraleidolia. 
Let's explote how the brain works, not how we want it to work.

Nobody wants more data. They want answers. They want emotions. They want change.

Tufte was the first "data storyteller" - he was against the "data dump" and power point.



